#!/usr/bin/env python3
"""Build current pages from measured H4 evidence; never invent a score or promote."""
from __future__ import annotations
from html import escape as esc
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
PROBLEM = "https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/"
BOARD = "https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/"
RULES = "https://docs.nlr.gov/docs/fy26osti/96647.pdf"
REID = "https://www.reid-geophys.co.uk/wp-content/uploads/2017/11/Reid-et-al-1990.pdf"
SI = "https://www.reid-geophys.co.uk/wp-content/uploads/2017/11/Reid-Thurston-2014.pdf"


def load(name):
    return json.loads((DOCS / "data" / name).read_text())


def page(name, title, body, active):
    nav = [("index.html", "Overview"), ("executive-summary.html", "Submission guide"),
           ("evidence.html", "Evidence"), ("hypotheses.html", "Hypotheses"), ("sources.html", "Research library")]
    links = "".join(f'<a class="{"active" if file == active else ""}" href="{file}">{text}</a>' for file, text in nav)
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)} · GEMSDOE40</title><meta name="description" content="Measured Euler depth-clustering research for geological fault mapping. A unique GeoTIFF, open evidence, and an honest no-submission gate.">
<link rel="stylesheet" href="assets/contact.css"><script src="assets/contact.js" defer></script></head>
<body><a href="#main" class="skip">Skip to content</a><header class="header"><div class="wrap"><div class="masthead">
<a class="brand" href="index.html"><span class="brand-icon" aria-hidden="true">G</span><b>GEMS / 40</b><em>FIELD NOTES</em></a><nav class="nav" aria-label="Main navigation">{links}</nav></div></div></header>
<main id="main" class="wrap">{body}</main><footer class="footer"><div class="wrap"><p><strong>Maximize P(Win). Own the Outcome.</strong><br>Evidence before a weekly submission slot.</p>
<p>Independent competition research · not affiliated with DOE or DrivenData.<br><a href="https://github.com/buffedlizard55-lab/GEMSDOE40">Repository</a> · <a href="user-prompt-20261006.md">Full project brief</a> · <a href="reports/review-20261006.md">Three-pass review</a></p></div></footer></body></html>'''
    (DOCS / name).write_text(html, encoding="utf-8")


def subhero(kicker, title, lead):
    return f'<div class="subhero"><p class="kicker">{kicker}</p><h1>{title}</h1><p class="lead">{lead}</p></div>'


def main():
    c, g, u, v = (load(n) for n in ("current-candidate.json", "h4-generation.json", "h4-uniqueness.json", "h4-validation.json"))
    h33, official, projects = (load(n) for n in ("h33-measured-analysis.json", "official-observation-20261006.json", "project-site-review-20261006.json"))
    inv = load("prior-inventory-20261006.json")
    assert u["uniqueness_pass"] and g["candidate_format"]["valid"]
    assert u["inventory_blobs"] == u["hashed_and_audited_blobs"] == len(inv["unique_rasters"])
    assert c["sha256"] == v["candidate_sha256"] == u["candidate_sha256"]
    assert c["slot_eligible"] is False, "Review promotion copy before changing the site's no-go status"
    mag, grav = g["families"]["tmi"]["kde"], g["families"]["iso_grav_anom"]["kde"]
    clustered = mag["clustered_solutions"] + grav["clustered_solutions"]
    score = v["candidate_score"]["pooled"]["score"]
    frozen = v["baselines"]["frozen_sgmc_derived_incumbent"]["score"]["pooled"]["score"]
    h33score = v["baselines"]["h33_b2_owner_reported_02778"]["score"]["pooled"]["score"]
    previous = v["baselines"]["h2b_previous_research"]["score"]["pooled"]["score"]
    link = "downloads/" + c["filename"]
    download = f'<a class="button" href="{link}" download>Download new research GeoTIFF <span aria-hidden="true">↓</span></a>'
    hold = '<span class="tag hold">HOLD — DO NOT SUBMIT</span>'
    def results_table():
        return f'''<div class="tablewrap"><table><thead><tr><th>Same blocked SGMC proxy</th><th>DTI</th><th>Interpretation</th></tr></thead><tbody>
<tr class="row-h4"><td><strong>H4 · new depth-KDE</strong></td><td class="num">{score:.6f}</td><td>0/16 truth-bearing block wins against either comparator below.</td></tr>
<tr><td>H33-B2 · owner’s reference</td><td class="num">{h33score:.6f}</td><td>Diagnostic only; not the owner-reported 0.2778 leaderboard score.</td></tr>
<tr><td>Frozen all-prior incumbent</td><td class="num">{frozen:.6f}</td><td>SGMC-derived: circular on this proxy.</td></tr>
<tr><td>H2-B · previous research</td><td class="num">{previous:.6f}</td><td>Also failed promotion; not a meaningful quality target.</td></tr></tbody></table></div>'''

    body = f'''<section class="hero"><div><p class="kicker">EXPERIMENT H4 / GEODAWN, NEVADA / 06 OCT 2026</p>
<h1>Depth,<br>not just <em>edges.</em></h1><p class="lead">A new fault-confidence raster built from magnetic and gravity source depths. Real Euler solutions, a continuous density field, and an audit you can inspect.</p>
{hold}<div class="download">{download}</div><p class="file-details">3.92 MB · single-band float32 · EPSG:32611<br>100 m · 3,730 rows × 3,292 columns · [0, 1]<br>NaN only outside the sample footprint</p>
<div class="notice"><strong>New file. Not a proven improvement.</strong><p>The raw-output and format audits pass. The blocked proxy test does not. Download for research; do not spend a weekly slot on this version.</p></div>
<div class="actions"><a class="textlink" href="executive-summary.html">File, name &amp; submission guide ↗</a><a class="textlink" href="evidence.html">Inspect the evidence ↗</a></div>
</div><div class="map-panel"><a href="assets/h4-raster.png"><img src="assets/h4-raster.png" alt="Actual H4 continuous Euler solution-density raster on the GeoDAWN footprint, in UTM zone 11N" width="1005" height="1185"></a><div class="map-foot"><span>MODEL OUTPUT / NOT OBSERVED FAULTS</span><b>OPEN MAP ↗</b></div></div></section>
<div class="checkstrip"><div><span class="stat">{clustered:,}</span><span class="label">Clustered depth solutions</span></div><div><span class="stat">{u['inventory_blobs']}</span><span class="label">Prior artifacts audited</span></div><div><span class="stat">{u['max_abs_pearson']:.4f}</span><span class="label">Largest raw |correlation|</span></div><div><span class="stat">0</span><span class="label">Competition slots used</span></div></div>
<section class="section" id="research"><div class="sectionhead"><div><p class="eyebrow">01 / A DIFFERENT PHYSICAL SIGNAL</p><h2>From source depth to a map.</h2></div><a href="methodology.html">Full method &amp; assumptions ↗</a></div>
<div class="grid3"><article class="card"><span class="stepnum">01 — INVERT</span><h3>Solve for the contact.</h3><p>Fit Reid’s SI=0 contact equation, including its offset A. A rank-aware solve retains straight contacts without pretending to know their along-strike position.</p></article>
<article class="card"><span class="stepnum">02 — TEST CONSISTENCY</span><h3>Keep coherent depths.</h3><p>{mag['clustered_solutions']:,} magnetic and {grav['clustered_solutions']:,} gravity solutions survive cross-window depth checks. Deep, uncertain and scattered solutions receive less weight.</p></article>
<article class="card"><span class="stepnum">03 — ESTIMATE DENSITY</span><h3>Map the point cloud.</h3><p>Weighted Gaussian KDE becomes a continuous [0,1] confidence field. No gradient threshold, inherited prediction map, top-k dot budget, or random perturbation.</p></article></div></section>
<section class="section" id="decision"><div class="sectionhead"><div><p class="eyebrow">02 / THE RESULT, WITHOUT THE SPIN</p><h2>Format passes. Promotion does not.</h2></div><a href="evidence.html">All checks &amp; limitations ↗</a></div>{results_table()}
<p class="micro">These are owner-derived SGMC proxy scores, not organizer scores. The historical gate also requires 18 strict block wins when only 16 blocks contain truth. That defect is disclosed, not silently relaxed.</p></section>
<section class="section twocol"><div class="callout"><p class="eyebrow">03 / WHY THE PREVIOUS BEST HELPED</p><h3>Fewer predictions.<br>Not more discovered faults.</h3><p>We verified H33-B2 is exactly the 40,199-pixel reference with 2,545 catalogue-adjacent pixels removed. That can reduce the Tversky false-positive cost without adding any new geometry.</p><a class="textlink" href="leaderboard-analysis.html">What 0.2778 does—and doesn’t—tell us ↗</a></div>
<div class="callout" id="feed"><p class="eyebrow">04 / KEEP THE RECORD CURRENT</p><h3>An official-source feed,<br>not a submission bot.</h3><p id="feed-status" aria-live="polite">Loading the dated USGS context snapshot…</p><ul id="feed-events" class="eventlist"></ul><a class="textlink" href="sources.html#context">Sources, freshness &amp; access limits ↗</a></div></section>
<section class="section"><div class="reportline"><span>Official leaderboard observed 6 October: <strong>{official['top_rows'][0]['score']:.4f}</strong> at #1. Not a live scrape.</span><a href="{BOARD}">Open official board ↗</a></div><div class="reportline"><span>All {projects['project_count']} brief-listed projects; {projects['reported_score_count']} owner-reported scores; {len(inv['repository_snapshots'])} repositories inventoried.</span><a href="leaderboard.html">Complete project register ↗</a></div></section>'''
    page("index.html", "Depth, not just edges", body, "index.html")

    guide = subhero("EXECUTIVE SUMMARY / DOWNLOAD & DECISION", "One file. A clear decision.", "The new TIFF is submission-format valid and genuinely distinct from the inventoried prior outputs. It has not earned a competition slot.")
    guide += f'''<section class="section"><div class="twocol"><div>{hold}<div class="download">{download}</div><p class="micro">Download the .tif itself—not this web page, report, or preview image.</p><h3>Exact filename</h3><div class="codebox" id="filename">{esc(c['filename'])}</div><button class="copy" data-copy="filename">Copy filename</button><h3>Tracking name</h3><div class="codebox" id="submission-name">{esc(c['name'])}</div><button class="copy" data-copy="submission-name">Copy name</button></div>
<div class="callout"><p class="eyebrow">CURRENT DECISION</p><h3>Do not upload this version.</h3><p>H4’s {score:.6f} proxy DTI is below H33-B2’s {h33score:.6f}, and far below the circular frozen incumbent. No organizer score is available. No submission has been made.</p><p>Providing a valid file is not the same as recommending it. The user’s “beat the current holdout best first” rule is retained.</p><a href="evidence.html">Read the measured result ↗</a></div></div>
<h3>Short note · {c['note_characters']} characters · research record only</h3><div class="codebox" id="submission-note">{esc(c['note'])}</div><button class="copy" data-copy="submission-note">Copy note</button>
<h3>SHA-256 of the actual download</h3><div class="codebox" id="file-sha">{c['sha256']}</div><button class="copy" data-copy="file-sha">Copy SHA-256</button><p class="micro"><a href="data/h4-format.json">Independent disk re-read</a> · <a href="data/h4-uniqueness.json">Every raw-output comparison</a> · <a href="downloads/h4-submission-note.txt">Name and note as text</a></p></section>
<section class="section prose"><h2>How a future approved submission is entered</h2><p><strong>These are future instructions, not permission to submit H4.</strong> First require a reproducible, valid independent gate win, plus complete novelty and format passes. The historical gate must be repaired in a separately registered protocol—not after choosing a result.</p>
<ol><li>Open the <a href="{PROBLEM}">official competition</a> in your own account. Confirm eligibility, enrollment and current rules. No passwords or tokens should be put in this repository.</li><li>Download the exact approved <strong>.tif</strong> using the prominent button. Compare its SHA-256 with its receipt. Do not upload an HTML file saved by the browser.</li><li>Open <strong>New submission</strong>. In <strong>File to submit</strong>, choose the downloaded GeoTIFF. The optional alternative is a ZIP containing exactly one GeoTIFF; this project supplies the TIFF directly.</li><li>Paste the approved short note into <strong>Note (optional)</strong>. Keep the unique tracking name and full SHA-256 in the local experiment record.</li><li>Only then submit, review the server’s validation response, and save the actual file-level score receipt. An account’s best leaderboard row is not a receipt for a particular file.</li><li>Respect the <a href="{RULES}">three-per-week limit</a>. Choose one final submission for both prize rounds under the current rules. This research pipeline never performs a DrivenData upload.</li></ol>
<h2>Preventing “Predicted values must be in range [0, 1]”</h2><p>The written H4 file was reopened and checked across <strong>all 5,167,373 valid pixels</strong>: every value is finite and within [0,1]. All 7,111,787 outside pixels are NaN, matching the sample mask. The feature stack’s −3.4028235e38 sentinel is never copied into predictions.</p><p>NaN outside is the requested and documented format. We do <strong>not</strong> claim NaN itself causes rejection, and do not silently replace the footprint contract with zeros everywhere. A local pass is not a guarantee about an unknown server-side validator; if a future authorized upload fails, retain the exact bytes and error for diagnosis.</p>
<h2>Rebuild, don’t rename an old TIFF</h2><div class="codebox code">python3 -m venv .venv
. .venv/bin/activate
python -m pip install -r requirements-research.txt
python -m pip install -e .
bash scripts/download_competition_data.sh
python scripts/prepare_data.py
python scripts/fetch_prior_cache.py --inventory docs/data/prior-inventory-20261006.json --cache data/prior
OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=2 python scripts/run_contact_euler.py
OPENBLAS_NUM_THREADS=1 python scripts/audit_contact_candidate.py
python scripts/build_site.py --check</div><p>CPU-only. The 419 MB feature stack and prior cache are restored automatically from pinned public mirrors; no GPU training is required for Euler inversion. Source links and mirror-provenance limits are in the <a href="sources.html">research library</a>.</p>
<p><a href="https://github.com/buffedlizard55-lab/GEMSDOE40/actions/workflows/reproduce.yml">Reproduction workflow ↗</a> · <a href="downloads/h4-euler-solutions.csv.gz">Download all 46,656 QC-passing depth solutions (CSV.gz)</a></p><p class="micro">Historical status: HOLD — DO NOT SUBMIT H2-B. Previous files remain archived for learning and are not the current download.</p></section>'''
    page("executive-summary.html", "Executive summary and submission guide", guide, "executive-summary.html")

    closest = "".join(f'<tr><td>{esc(r["artifact"]["repo"])}<br><span class="mono">{esc(Path(r["artifact"]["path"]).name)}</span></td><td class="num">{r["pearson_r"]:.6f}</td><td class="num">{r["top_jaccard"]:.6f}</td></tr>' for r in u["closest_by_pearson"])
    evidence = subhero("AUDIT / NO SELECTIVE REPORTING", "Evidence you can inspect.", "Hashes prove artifact identity. Analytic tests check the inversion. A proxy test measures a limited outcome. None of these alone establishes a new fault or a leaderboard win.")
    evidence += f'''<section class="section">{results_table()}<div class="notice"><strong>Two independent reasons not to promote.</strong><p>H4 loses to H33-B2 in every truth-bearing block. Separately, the inherited 18-of-24 rule is impossible because eight blocks have no truth. The SGMC-derived incumbent is circular on the SGMC proxy. We preserve these negative findings and do not relabel them as an independent validation success.</p></div>
<div class="grid3"><div class="card"><span class="tag pass">Format pass</span><h3>Exact template contract.</h3><p>One float32 band. EPSG:32611, 100 m, 3,730 × 3,292. Exact affine transform and footprint. Finite [0,1] inside; NaN only outside.</p><a href="data/h4-format.json">Re-read receipt ↗</a></div>
<div class="card"><span class="tag pass">Uniqueness pass</span><h3>Raw values, not previews.</h3><p>{u['inventory_blobs']} byte-verified artifacts; {u['exact_grid_comparisons']} exact-grid and {u['full_size_raw_comparisons']} full-size array comparisons. A spatial format fixture, a one-pixel demo and a header-only non-raster are explicitly distinguished from prediction maps.</p><a href="data/h4-uniqueness.json">Full comparison table ↗</a></div>
<div class="card"><span class="tag hold">Promotion fail</span><h3>No weekly slot.</h3><p>0 block wins against both H33-B2 and the frozen incumbent. This is a new scientific implementation, not a proven improvement. No organizer score exists.</p><a href="data/h4-validation.json">Every block and comparator ↗</a></div></div></section>
<section class="section"><div class="sectionhead"><div><p class="eyebrow">NOVELTY / LOCKED BEFORE SCORING</p><h2>Not a re-packaged previous submission.</h2></div></div><p class="soft">Reject identical file or canonical pixel hashes, |Pearson| ≥0.85, top-37,654 positive-cell Jaccard ≥0.50, or containment ≥0.80. All pixels are compared—not a random sample. Three legacy nodata=0 tags are treated as raw stored zero predictions, not used to hide absence pixels.</p>
<div class="tablewrap"><table><thead><tr><th>Closest prior outputs by |r|</th><th>Pearson r</th><th>Top-budget Jaccard</th></tr></thead><tbody>{closest}</tbody></table></div><p class="micro">Maximum top Jaccard: {u['max_top_jaccard']:.6f}; maximum top containment: {u['max_top_containment']:.6f}; near-duplicates: {u['near_duplicate_count']}. Historical H2-B rules also flag {u['historic_h2b_rule_flags']} matches. Scope: {len(inv['repository_snapshots'])} public repositories, 333 pinned public branch heads, 1,835 reachable commits and {len(inv['zip_archives_checked'])} inspected ZIP paths/versions. Unreachable/private artifacts and later pushes are not claimed.</p>
<p class="micro">Two older NaN exports have invalid inside-footprint masks. Their actual finite values are compared as stored; exact whole-array equality to separately published all-finite companions proves the missing cells are only zero-storage variants. The companions supply the complete comparisons. Nothing is silently imputed. <a href="data/prior-nonprediction-forensics-20261006.json">Header/demo forensics</a> · <a href="data/prior-exclusion-review-20261006.json">Every excluded source path</a>.</p><div class="twocol comparison"><figure><a href="assets/h4-raster.png"><img loading="lazy" src="assets/h4-raster.png" alt="New H4 depth-KDE on the template grid"></a><figcaption>H4: continuous weighted depth-solution density.</figcaption></figure><figure><a href="assets/h33-raster.png"><img loading="lazy" src="assets/h33-raster.png" alt="Historical H33-B2 dotted prediction on the same extent and color scale"></a><figcaption>H33-B2: historical binary dotted geometry. Both previews use the same 0–1 color range and 4×4 maximum pooling for visibility; TIFFs are unmodified.</figcaption></figure></div></section>
<section class="section prose"><h2>Reproducibility and verification passes</h2><p>Pass 1 restored pinned inputs, registered H4–H7, implemented analytic contact tests, and generated the complete Euler clouds. Pass 2 identified and fixed the nodata-zero comparison bug, incomplete old downloads and fail-open novelty behavior; it also audited archived/raw model outputs and ZIPs. Pass 3 reproduces the exact candidate, checks the current site and download, and verifies CI/PR/deployment separately.</p><p><a href="reports/review-20261006.md">Full three-pass ledger</a> · <a href="data/h4-reproduction.json">Measured reproduction receipt</a> · <a href="reports/h4-results-20261006.md">Human-readable result</a> · <a href="research/h4-preregistration-20261006.md">Unchanged registration</a></p>
<h2>What cannot be claimed</h2><ul><li>No independently verified unknown-fault truth set or competition score for H4.</li><li>No proof that a modeled contact is a fault, geothermal vent, fluid conduit, or viable reservoir.</li><li>No claim that overlapping windows are independent measurements or that conditional least-squares standard errors include terrain/processing bias.</li><li>No authentication of the source mirrors by the organizer. The input hashes prove consistency, not provenance beyond their documented public bridge.</li></ul>
<p><a href="data/h4-generation.json">Configuration, input and code hashes</a> · <a href="data/prior-inventory-20261006.json">Every prior path and pinned revision</a> · <a href="data/acquisition-20261006.json">Acquisition receipt</a></p></section>'''
    page("evidence.html", "Evidence and validation", evidence, "evidence.html")

    hypotheses = subhero("RESEARCH / REGISTER BEFORE IMPLEMENTATION", "Four hypotheses.<br>One frozen experiment.", "Ranked by expected scientific value for DTI improvement, not invented score forecasts. H4 was implemented first; H5–H7 have not been tuned against the H4 result.")
    hypotheses += '''<section class="section"><div class="tablewrap"><table><thead><tr><th>Rank / hypothesis</th><th>Layers and physical signature</th><th>Off-catalogue rationale &amp; difference</th><th>Expected gain / cost</th></tr></thead><tbody>
<tr class="row-h4"><td><strong>1 · H4</strong><br>Offset-aware, rank-adaptive contact Euler</td><td>TMI + first vertical gravity derivative; SI=0+A, cross-window depth clusters, continuous KDE.</td><td>Buried straight contacts can be rejected by old full-rank/A=0 solvers. Explicitly models the unresolved strike direction; no inherited map or dot-thinning.</td><td>Best expected recovery of the observed physics failure; DTI direction unknown. Medium cost. <strong>Implemented; proxy gate failed.</strong></td></tr>
<tr><td><strong>2 · H5</strong><br>Finite density-step inversion</td><td>Raw isostatic gravity + TMI; explicit top and bottom source edges, density contrast, nonlinear residual comparison.</td><td>Cancellation between finite source edges may hide low-throw buried faults. Unlike H4, it models both edges rather than a local top-edge approximation.</td><td>Potential specificity gain, substantial non-identifiability. High cost. Existing fields suffice for a test; not implemented.</td></tr>
<tr><td><strong>3 · H6</strong><br>Depth-cloud plane geometry</td><td>Multi-depth TMI/gravity cloud; robust planes and coherent dip-related source migration.</td><td>A dipping fault’s subsurface source need not lie below its surface trace. Different from height persistence or catalogue tip extension.</td><td>Possible localization gain; high extrapolation risk and cost. Reference-plane test only. Ground-surface projection blocked by unverified survey datum.</td></tr>
<tr><td><strong>4 · H7</strong><br>Representation stability</td><td>TMI vs RTP Euler positions, checked against gravity while accounting for correlated magnetic representations.</td><td>Reject processing-related magnetic solutions without treating TMI and RTP as independent confirmations. H2 varied height, not representation.</td><td>Possible precision gain but may reject real remanent sources. Medium cost. Existing layers; not implemented.</td></tr></tbody></table></div></section>'''
    hypotheses += f'''<section class="section prose"><h2>One important viability boundary</h2><p>H6 needs verified altitude and datum information before projecting to the ground surface. The free official <a href="https://doi.org/10.5066/P93LGLVQ">USGS GeoDAWN release</a> lists flight-line CSVs and contractor reports. Metadata is obtainable; complete payload access and suitable datum information have not been verified. We therefore do not call that ground-projection variant viable.</p><h2>What is novel here—and what isn’t</h2><p>Euler inversion, contact offsets and rank reduction are established mathematics. The specific corrected dual-field construction is different from the inspected repository implementations, and its raster passes the dated all-prior audit. That is a bounded method/artifact claim, not a claim to invent Euler theory.</p><h2>What happens next</h2><ol><li>Register a new, feasible, independent whole-fault-system holdout protocol. Keep the old gate/results intact; do not use H4’s failure to lower a success threshold retroactively.</li><li>Audit the native gravity bandwidth and survey drape datum. Synthetic planar success is necessary but not sufficient for a real depth interpretation.</li><li>Test H5 on synthetic finite steps, then a locked geologic benchmark, before considering another competition slot.</li></ol><p><a href="research/h4-preregistration-20261006.md">Read every frozen setting and gate</a> · <a href="research/hypotheses.md">Earlier append-only H1–H3 history</a></p></section>'''
    page("hypotheses.html", "Ranked hypotheses", hypotheses, "hypotheses.html")

    method = subhero("METHOD / POTENTIAL-FIELD INVERSION", "A cloud of depths.<br>Not a thresholded edge map.", "The prediction values come from fitted source locations and their depth consistency, not magnetic or gravity gradient magnitudes.")
    method += f'''<section class="section prose"><h2>The equation the old model omitted</h2><div class="formula">(x − x₀) Fₓ + (y − y₀) Fᵧ + (z − z₀) Fz = A<br>At z = 0: x Fₓ + y Fᵧ = x₀ Fₓ + y₀ Fᵧ + z₀ Fz + A</div><p><a href="{REID}">Reid et al. (1990), equation 2 and step 3b</a>, solve for A for a general SI=0 magnetic contact. H4 profiles out that offset by centering the gradient columns and right-hand side. Horizontal coordinates are east/north in metres; depth is positive down.</p><p>A straight contact does not identify position along strike. The local horizontal derivative tensor selects a cross-strike/depth solve when its minor/major eigenvalue ratio is at most 0.10; otherwise H4 fits 3-D position. The unresolved coordinate is anchored at the window center and recorded as rank 2, not reported as measured.</p>
<h2>Gravity requires a different physical interpretation</h2><p>SI=0 on <strong>raw gravity</strong> is not the same magnetic-contact model. <a href="{SI}">Reid &amp; Thurston (2014)</a> correct the finite gravity-step index and explain the need for generalized source geometry. H4 inverts the first vertical derivative of gravity at SI=0 as a local top-edge approximation. A finite bottom edge, remanence, regional trends and terrain can still bias these solutions.</p>
<h2>Locked parameters, not a holdout search</h2><div class="tablewrap"><table><thead><tr><th>Operation</th><th>Magnetics</th><th>Gravity</th></tr></thead><tbody><tr><td>Named source band</td><td>tmi, measured band 14</td><td>iso_grav_anom, measured band 13</td></tr><tr><td>Upward continuation</td><td>200 m</td><td>500 m, then dG/dz</td></tr><tr><td>Full-resolution windows / stride</td><td>15 and 25 cells / 5</td><td>31 and 51 cells / 5</td></tr><tr><td>Invalid-data guard</td><td>1,500 m plus full window</td><td>3,000 m plus full window</td></tr><tr><td>Effective depth interval</td><td>100–5,000 m</td><td>100–8,000 m</td></tr><tr><td>Clustered solutions</td><td>{mag['clustered_solutions']:,}</td><td>{grav['clustered_solutions']:,}</td></tr><tr><td>Median effective depth</td><td>{mag['depth_m_p05_p50_p95'][1]:.1f} m</td><td>{grav['depth_m_p05_p50_p95'][1]:.1f} m</td></tr></tbody></table></div>
<p>The centered relative fit residual must be ≤0.30; scaled design condition ≤1,000; location within a half-window; conditional depth error ≤max(100 m, 25% of depth). Errors exclude correlated survey noise and model mismatch. Continuation height is subtracted exactly once.</p>
<h2>From point support to continuous confidence</h2><p>Neighbours within 600 m XY and max(250 m, 35% of depth) supply a consistency weight. At least two other neighbours and the other window scale are required. Weights penalize depth, fit error, depth uncertainty and robust depth scatter; neighbour count saturates to avoid unbounded repeated-window voting.</p><p>Bilinear point deposition and a 200 m Gaussian kernel make the density field. Each family is normalized by its positive 99.5th percentile, clipped to [0,1], then combined as (M + G + √(MG))/3. After exact known-pixel suppression, the field is max-normalized. Unsupported cells are zero. Only outside-footprint cells are NaN.</p><p>The result has {g['positive_pixels']:,} positive cells, {g['unique_finite_prediction_values']:,} distinct finite values, and total confidence mass {g['in_footprint_mass']:,.2f}. It is <strong>not a calibrated probability</strong> and not a binary map.</p><p><a href="data/h4-generation.json">Every parameter, rejection count and input hash</a> · <a href="research/h4-preregistration-20261006.md">Preregistration</a></p></section><section class="section twocol"><figure class="map-panel"><a href="assets/h4-depth-cloud.png"><img loading="lazy" src="assets/h4-depth-cloud.png" alt="Actual clustered Euler solutions colored by effective depth below the reference observation plane"></a><figcaption>Depth-labeled magnetic and gravity solutions. These are source hypotheses, not observed fault traces.</figcaption></figure><div class="prose"><h2>Read the actual cloud.</h2><p>The compressed CSV contains all 46,656 QC-passing solutions, including points assigned zero clustering weight. It records family, window, projected XY, effective depth, conditional error, residual, condition, contact offset, rank, neighbours and weight.</p><p><a class="button secondary" href="downloads/h4-euler-solutions.csv.gz" download>Download solution cloud ↓</a></p><p>Unresolved strike position and a terrain-draped survey limit interpretation. These depths are relative to the input reference observation plane—not independently verified ground-depth estimates.</p></div></section>'''
    page("methodology.html", "Euler method", method, "hypotheses.html")

    analysis = subhero("LEADERBOARD ANALYSIS / MEASURED, NOT INFERRED", "Why did H33-B2 help?", "The owner reports 0.2778 for H33-B2. We verified the raster’s identity and geometry, but the public board does not provide a file-level receipt proving that attribution.")
    analysis += f'''<section class="section twocol"><div class="callout"><p class="eyebrow">WHAT THE FILES PROVE</p><span class="big">2,545</span><h3>pixels removed. Zero added.</h3><p>H33-B2 is exactly the 40,199-pixel H27-4 base pruned at ≤200 m from the known catalogue. It leaves 37,654 pixels: 6.33% fewer. The removed pixels are 141.4–200 m from catalogue pixels.</p><a href="data/h33-measured-analysis.json">Byte identities and exact-set proof ↗</a></div><div class="callout"><p class="eyebrow">WHAT THE BOARD DOES NOT PROVE</p><h3>A better detector?<br>Not established.</h3><p>No new fault positions were added by that change. The plausible score mechanism is less false-positive mass for similar true-positive coverage. Private labels are unavailable, so that causal explanation remains conditional.</p><p>The official board’s leading score was <strong>0.3345</strong> on 6 October, not 0.3195. Account-level rows do not identify their TIFF.</p><a href="{BOARD}">Official leaderboard ↗</a></div></section>
<section class="section prose"><h2>The metric explains the tradeoff precisely</h2><p>Let T be distance-weighted true-positive credit, F the weighted false-positive mass, and G the number of truth pixels. The <a href="{PROBLEM}">published metric</a> simplifies to:</p><div class="formula">D = T / (0.2T + 0.2F + 0.8G + ε)<br>Removing predictions improves D exactly when:<br>(1 − 0.2D) × lost TP credit &lt; 0.2D × saved FP mass</div><p>At D=0.2778, losing less than <strong>0.05883</strong> units of TP credit per unit of saved FP mass improves the score. Thus pruning redundant/incorrect predictions can help without discovering anything new. It does not justify deleting all catalogue-adjacent structures: the <a href="https://community.drivendata.org/t/scoring-clarification-are-known-usgs-ingenious-faults-masked-when-scoring-and-are-they-in-the-final-round-label-set/11516/4">organizer confirms</a> that new faults may lie within 300 m of known traces.</p>
<h2>Can we beat 0.2778—or 0.3345?</h2><p>It is a reasonable research goal, not a defensible promise from the available data. Holding F and G fixed, moving from 0.2778 to 0.3345 would require about <strong>21.87% more weighted TP credit</strong>. That is an algebraic scenario, not a predicted score; a real model changes both T and F.</p><p>H4 deliberately tries new source geometry instead of copying and thinning H33. It passes novelty but obtains only {score:.6f} on the local proxy versus H33-B2’s {h33score:.6f}. We therefore have <strong>no evidence that H4 beats the owner’s best</strong>. It is not submitted.</p><h2>The next high-value work</h2><ol><li>Replace the circular/impossible promotion instrument in a separately preregistered experiment with independent, whole-fault-system validation.</li><li>Test finite-step gravity models and survey-datum-corrected source localization; use synthetic known-depth controls before region-wide inference.</li><li>Separate detection skill from output mass. Compare methods at matched confidence mass and evaluate native continuous outputs, without reusing the test fold to tune emission.</li><li>For geothermal interpretation, require independent geologic/thermal corroboration rather than equating every potential-field contact with a permeable fault.</li></ol><p><a href="research/scientific-library-20261006.md">Research basis and limitations</a> · <a href="leaderboard.html">Every user-reported score</a></p></section>'''
    page("leaderboard-analysis.html", "Understanding the 0.2778 reference", analysis, "evidence.html")

    rows = []
    for project in projects["projects"]:
        subs = project["submissions"]
        details = "<ul class=\"submissions\">" + "".join(f'<li>{esc(s["name"])}<br><strong>{s["score"]:.4f}</strong> · owner report</li>' if s['score'] is not None else f'<li>{esc(s["name"])}<br>Score not supplied</li>' for s in subs) + "</ul>" if subs else "No submission/score supplied in brief."
        source = project.get("page_source", {})
        source_link = f'<a href="{esc(source.get("url", project["site"]))}">Pinned page source ↗</a>'
        rows.append(f'<tr data-project-row><td><a href="{esc(project["site"])}"><strong>{esc(project["repo"])}</strong></a></td><td>{details}</td><td class="num">{project["audited_unique_tiff_blobs"]}</td><td>{source_link}<br><span class="micro">{esc(source.get("commit", "")[:10])}</span></td></tr>')
    history = subhero("COMPLETE REGISTER / ALL BRIEF-LISTED PROJECTS", "Keep the claims<br>and the evidence separate.", f"{projects['project_count']} projects, {projects['reported_score_count']} supplied scores. Null scores remain unknown. Page source was read at pinned GitHub revisions; this is not a live-site uptime claim or an organizer receipt.")
    history += f'''<section class="section"><div class="notice"><strong>Last official observation: 0.3345 leading, 6 October 2026.</strong><p>0.2778 appears as an account-level public score. The association with H33-B2 below is the owner’s report, not independently proved by that leaderboard row. No scheduled DrivenData scrape is running.</p></div><label for="project-search" class="label">Filter projects, filenames or reported scores</label><br><input class="search" id="project-search" type="search" placeholder="e.g. 0.2778, Euler, GEMSDOE32"><p class="micro" id="search-count" aria-live="polite">{projects['project_count']} project rows shown</p>
<div class="tablewrap"><table class="scorelist"><thead><tr><th>Project / site</th><th>Submission and owner-reported score</th><th>Audited TIFF blobs</th><th>Source review</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div><p class="micro">Counts include historical and experimental outputs, not only competition submissions. A shared blob may appear under multiple projects. The broader raw-output census spans {len(inv['repository_snapshots'])} repositories and {u['inventory_blobs']} distinct TIFF-named artifacts (333 full-size maps, plus separately classified fixtures/malformed header).</p><div class="linkrow"><a href="data/project-site-review-20261006.json">Complete page/score JSON</a><a href="data/prior-inventory-20261006.json">Immutable artifact inventory</a><a href="data/official-observation-20261006.json">Dated board observation</a></div></section>'''
    page("leaderboard.html", "Complete project and score register", history, "evidence.html")

    source_rows = [
        ("Official competition", "Task, metric and format", PROBLEM, "Geological fault confidence, not vent detection. 300 m distance-weighted Tversky; exact raster requirements."),
        ("Official rules", "DOE / NLR · September 2026", RULES, "Weekly limits, finalist reproducibility, and one selection for both rounds. No competition submission was made."),
        ("Scientific primary source", "Reid et al. · 1990", REID, "Contact Euler needs the arbitrary offset A. Source-position/depth inference is not a proof of a fault."),
        ("Scientific correction", "Reid & Thurston · 2014", SI, "Gravity/magnetic SI distinctions and limitations of single-source homogeneity for finite steps."),
        ("Official USGS · CC0 metadata", "GeoDAWN survey release", "https://www.usgs.gov/data/geodawn-airborne-magnetic-and-radiometric-surveys-northwestern-great-basin-nevada-and", "Terrain-draped magnetic/radiometric survey, variable clearance, 200/400 m nominal flight-line spacing. Metadata obtainable; altitude bulk audit still needed."),
        ("Official USGS", "Regional geophysical maps", "https://www.sciencebase.gov/catalog/item/628d4fabd34ef70cdba3c4a4", "Provisional, multi-source regional gravity compilation. Resampling does not create independent 100 m observations."),
        ("Official GDR · CC-BY-4.0", "INGENIOUS collection 1391", "https://gdr.openei.org/submissions/1391", "Free faults, geodesy, seismicity, shallow temperatures, paleo-geothermal features and well/spring chemistry. Coverage and observational bias need auditing."),
        ("Official USGS", "State Geologic Map Compilation", "https://pubs.usgs.gov/ds/1052/", "Original compilation context only. Does not authenticate the owner-derived SGMC raster used as a proxy here."),
        ("Official USGS publication", "Blind Gabbs Valley geothermal discovery", "https://pubs.usgs.gov/publication/70201803", "The reported discovery combined structural, geophysical, temperature and geochemical evidence and drilling. It does not validate an isolated Euler cluster."),
        ("Official USGS publication", "Structural discontinuities · Siler 2023", "https://www.usgs.gov/publications/structural-discontinuities-and-their-control-hydrothermal-systems-great-basin-usa", "Process-based stress/strain context for fault terminations and stepovers. Geometric favorability is not measured geothermal permeability."),
        ("Organizer staff", "Pixel-exact known-fault mask", "https://community.drivendata.org/t/scoring-clarification-are-known-usgs-ingenious-faults-masked-when-scoring-and-are-they-in-the-final-round-label-set/11516/4", "No automatic 300 m exclusion buffer. Off-mask predictions near an old trace can still incur penalties."),
        ("Official platform policy", "DrivenData Terms of Use", "https://www.drivendata.org/termsofuse/", "Automated monitoring is restricted. The scheduled feed below only uses USGS/GDR, not DrivenData."),
    ]
    cards = "".join(f'<article class="sourcecard"><span class="label">{esc(kind)}</span><h3><a href="{url}">{esc(title)} ↗</a></h3><p>{esc(fact)}</p></article>' for kind, title, url, fact in source_rows)
    sources = subhero("RESEARCH LIBRARY / OFFICIAL & PRIMARY SOURCES", "Sources with boundaries.", "Every source has a role and a limit. Official context does not authenticate a mirror; an academic method does not guarantee a resource; a proxy result is not a leaderboard score.")
    sources += f'''<section class="section twocol"><div>{cards}</div><aside><div class="callout"><p class="eyebrow">DATA PLACEMENT / COMPLETED</p><h3>Inputs restored autonomously.</h3><p>The 419 MB feature stack, template, known labels and exact frozen proxy are in data/. Every part and assembled input is hash checked. Caches stay out of Git.</p><p><strong>No GPU is required</strong> for this Euler experiment. No DrivenData login or private labels are available.</p><a href="data/acquisition-20261006.json">Source pins and receipt ↗</a></div><div class="notice"><strong>Mirrors are not official authentication.</strong><p>GitHub-hosted sibling copies are used because direct sandbox HTTPS to official/Dropbox download hosts failed. Feature identity is consistency-checked, not certified by the organizer.</p></div><h3>Irregularities worth reviewing</h3><ul class="micro"><li>Same SGMC basename, three different rasters. Only the GEMSDOE30 pin reproduces the frozen instrument.</li><li>The supplied template has positive values despite an all-zero example description. It is used only for grid/footprint.</li><li>Ambiguous tc/depth band descriptions were not used as physical facts or H4 features.</li><li>H33’s 216-byte ZIP contains no TIFF; its actual TIFF was used for analysis.</li><li>History also contains a 110-byte header-only file and a one-pixel demo. They are byte-accounted, not falsely correlated.</li><li>Two old “NaN-outside” variants actually contain millions of NaNs inside the legal sample footprint. Their all-finite companions establish exact storage equivalence; H4 has no such missing inside pixels.</li><li>The frozen holdout gate is impossible and its incumbent circular.</li></ul><p><a href="research/scientific-library-20261006.md">Full claim-by-claim ledger</a></p></aside></section>
<section class="section" id="context"><p class="eyebrow">AUTOMATED CONTEXT / NO SCORE MONITORING</p><h2>USGS source freshness.</h2><p id="feed-status" aria-live="polite">Loading the dated official-source feed…</p><ul id="feed-events" class="eventlist"></ul><p class="micro">The Pages workflow refreshes the public ComCat context and USGS/GDR source probes daily. It preserves last-success timestamps, surfaces errors, and never changes the TIFF or promotes a candidate. Earthquakes are context, not confirmed faults or geothermal resources.</p><div class="linkrow"><a href="data/source-feed.json">Inspect source-feed JSON</a><a href="https://earthquake.usgs.gov/fdsnws/event/1/">Official ComCat API</a><a href="https://github.com/buffedlizard55-lab/GEMSDOE40/actions/workflows/pages.yml">Build / refresh history</a></div></section>'''
    page("sources.html", "Official-source research library", sources, "sources.html")
    root_landing = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0; url=docs/index.html"><title>GEMSDOE40 · H4 research download</title><link rel="canonical" href="docs/index.html"><link rel="stylesheet" href="docs/assets/contact.css"></head><body><main class="wrap subhero"><p class="kicker">GEMS / 40 · H4</p><h1>HOLD — DO NOT SUBMIT</h1><p>The new Euler depth-KDE is format-valid and distinct, but it failed proxy promotion. No weekly slot was used.</p><p><a class="button" href="docs/{link}" download>Download H4 research GeoTIFF ↓</a></p><p><a href="docs/index.html">Open the project site</a> · <a href="docs/executive-summary.html">Submission guide</a></p></main></body></html>'''
    (ROOT / "index.html").write_text(root_landing, encoding="utf-8")
    print("Built 8 evidence-driven pages and root redirect; no model, score, or promotion state changed.")


if __name__ == "__main__":
    main()
