#!/usr/bin/env python3
"""Build current pages from measured session-2 evidence; never invent a score or promote.

Session 2 candidates: H13 (crest-binary) and H8 (trace-locked depth-KDE).  Both HOLD.
Historical arms (H4, H7, H40, H4-A) retain their own receipts and no-go status.
"""
from __future__ import annotations
from html import escape as esc
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
PROBLEM = "https://www.drivendata.org/competitions/306/competition-doe-gems/page/967/"
BOARD = "https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/"
RULES = "https://docs.nlr.gov/docs/fy26osti/96647.pdf"
REID = "https://www.reid-geophys.co.uk/wp-content/uploads/2017/11/Reid-et-al-1990.pdf"
SI = "https://www.reid-geophys.co.uk/wp-content/uploads/2017/11/Reid-Thurston-2014.pdf"


def load(name):
    return json.loads((DOCS / "data" / name).read_text())


def page(name, title, body, active):
    nav = [("index.html", "Overview"), ("executive-summary.html", "Submission guide"),
           ("evidence.html", "Evidence"), ("hypotheses.html", "Hypotheses"), ("sources.html", "Research library")]
    links = "".join(f'<a class="{"active" if file == active else ""}" href="{file}">{text}</a>' for file, text in nav)
    html = f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{esc(title)} · GEMSDOE40</title><meta name="description" content="Measured Euler depth-clustering research for geological fault mapping. Unique GeoTIFFs, open evidence, honest no-submission gates.">
<link rel="stylesheet" href="assets/contact.css"><script src="assets/contact.js" defer></script></head>
<body><a href="#main" class="skip">Skip to content</a><header class="header"><div class="wrap"><div class="masthead">
<a class="brand" href="index.html"><span class="brand-icon" aria-hidden="true">G</span><b>GEMS / 40</b><em>FIELD NOTES</em></a><nav class="nav" aria-label="Main navigation">{links}</nav></div></div></header>
<main id="main" class="wrap">{body}</main><footer class="footer"><div class="wrap"><p><strong>Maximize P(Win). Own the Outcome.</strong><br>Evidence before a weekly submission slot.</p>
<p>Independent competition research · not affiliated with DOE or DrivenData.<br><a href="https://github.com/buffedlizard55-lab/GEMSDOE40">Repository</a> · <a href="user-prompt-20261006.md">Full project brief</a> · <a href="reports/session2-results-20261006.md">Session-2 results</a></p></div></footer></body></html>'''
    (DOCS / name).write_text(html, encoding="utf-8")


def subhero(kicker, title, lead):
    return f'<div class="subhero"><p class="kicker">{kicker}</p><h1>{title}</h1><p class="lead">{lead}</p></div>'


def main():
    c = load("current-candidate.json")
    h8u, h8v = load("h8-uniqueness.json"), load("h8-validation.json")
    h13u, h13v = load("h13-uniqueness.json"), load("h13-validation.json")
    h4g, h4u, h4v = load("h4-generation.json"), load("h4-uniqueness.json"), load("h4-validation.json")
    h33, official, projects = (load(n) for n in ("h33-measured-analysis.json", "official-observation-20261006.json", "project-site-review-20261006.json"))
    inv = load("prior-inventory-20261006.json")
    assert c["status"] == "HOLD — DO NOT SUBMIT" and c["slot_eligible"] is False, "review promotion copy before changing site no-go"
    assert h13v["gate"]["g2_uniqueness_pass"] and h8v["gate"]["g2_uniqueness_pass"]
    assert h13v["g1_format"]["valid"] and h8v["g1_format"]["valid"]
    g13, g8 = h13v["gate"], h8v["gate"]
    link = "downloads/" + c["filename"]
    h8link = "downloads/" + c["sibling_candidate"]["filename"]
    download = f'<a class="button" href="{link}" download>Download H13 research GeoTIFF <span aria-hidden="true">↓</span></a>'
    hold = '<span class="tag hold">HOLD — DO NOT SUBMIT</span>'

    def gate_rows(gate, name):
        d = gate
        return (f'<tr><td><strong>{name}</strong></td>'
                f'<td>{"✅" if d["g1_format_pass"] else "❌"} format</td>'
                f'<td>{"✅" if d["g2_uniqueness_pass"] else "❌"} uniqueness</td>'
                f'<td>{"✅" if d["g3_pass"] else "❌"} proxy holdout</td>'
                f'<td>{"✅" if d["g4_pass"] else "❌"} CAT-HID</td>'
                f'<td class="num">{d["g3_detail"]["candidate_pooled_dti"]:.6f}</td>'
                f'<td class="num">{d["g4_detail"]["candidate_cat_hidden_mean"]:.6f}</td></tr>')

    results_table = f'''<div class="tablewrap"><table><thead><tr><th>Candidate</th><th>G1</th><th>G2</th><th>G3 (gate bar 0.091550)</th><th>G4 (vs H33-B2 0.003590)</th><th>Proxy DTI</th><th>CAT-HID mean</th></tr></thead><tbody>
{gate_rows(g13, "H13 · crest-binary")}
{gate_rows(g8, "H8 · trace-locked KDE")}
<tr><td>H33-B2 · owner reference</td><td colspan="4">Diagnostic comparator on the same instruments — not the owner-reported 0.2778 leaderboard score.</td><td class="num">{g13["g3_detail"]["h33b2_pooled_dti"]:.6f}</td><td class="num">{g13["g4_detail"]["h33b2_cat_hidden_mean"]:.6f}</td></tr>
<tr><td>Frozen SGMC-derived incumbent</td><td colspan="4">Circular on the SGMC proxy; upper bound of SGMC-matching, not a target.</td><td class="num">0.835907</td><td class="num">—</td></tr></tbody></table></div>'''

    parallel = '''<section class="section" id="parallel-research"><p class="eyebrow">EARLIER ARMS / PRESERVED, NOT REBRANDED</p><h2>Nothing earlier is cleared either.</h2><div class="tablewrap"><table><thead><tr><th>Arm</th><th>Research files / record</th><th>Decision</th></tr></thead><tbody><tr><td>H4 · contact-offset depth-KDE (session 1)</td><td><a href="downloads/gemsdoe40-h4-contact-offset-depthkde-20261006-fab9f6619c02.tif" download>H4 GeoTIFF</a><br><a href="reports/h4-results-20261006.md">H4 result</a></td><td>HOLD. Proxy DTI 0.006902; 0/16 truth-bearing block wins. Its frozen solver output is the cloud H8/H13 re-use.</td></tr><tr><td>H7 · RTP Euler + gravity-gradient context</td><td><a href="downloads/gemsdoe40-h7-rtp-euler-gravity-context-3d-kde-20261006-998f660f.tif" download>H7 GeoTIFF</a><br><a href="reports/validation-h7-20261006.md">Record</a></td><td>HOLD. Uses the different 643cbe proxy version; do not mix its 0.000265 with 26d142 scores.</td></tr><tr><td>H40 · depth-cluster / dotted twins</td><td><a href="downloads/gemsdoe40-eulerdepth-si0-20261006-run2-57896abe-nan.tif" download>NaN twin</a> · <a href="downloads/gemsdoe40-eulerdepth-si0-20261006-run2-57896abe-zeros.tif" download>zero-outside twin</a> · <a href="downloads/gemsdoe40-eulerdepth-si0-20261006-run2-57896abe-audit.json">receipt</a></td><td>HOLD — DO NOT SUBMIT H40. Promotion estimates withdrawn by that session; zero-outside is not the footprint contract.</td></tr><tr><td>H4-A · contact network + terrain</td><td><a href="reports/h4a-negative-result-20261006.md">Negative result</a></td><td>Closed: 7.4× worse than chance on its own comparator.</td></tr></tbody></table></div><p class="micro">Unauthenticated file↔score attributions remain prohibited evidence, and its earlier calibration was withdrawn. The <a href="data/instrument-audit-20261006.json">parallel instrument audit</a> and <a href="data/unauthenticated_attribution_audit.json">attribution retraction</a> are retained but not adopted as a promotion gate. <a href="reports/integration-20261006.md">Integration notes</a>.</p></section>'''

    # Concurrent-session H8-ASA analytic-signal experiment (PR #13, merged from main).
    # Content mirrors docs/data/h8asa-*.json receipts; kept in the builder so the site
    # stays deterministic under `build_contact_site.py`.
    h8asa_index = '''<section class="section" id="h8asa"><div class="sectionhead"><div><p class="eyebrow">CONCURRENT SESSION / EXPERIMENT H8-ASA</p><h2>The analytic-signal variant: unique, gated, held.</h2></div><a href="reports/h8-results-20261006.md">Full measured result ↗</a></div>
<p>A parallel session registered a different H8 the same day: <strong>analytic-signal local-wavenumber depth cells</strong> (ASA/SPI family — tapered-FFT amplitude A=√(Tx²+Ty²+Tz²), contact depth z=√(A/|λ_min(Hessian A)|)), corroborated against the frozen H4 Euler cloud, KDE-smoothed into a continuous [0,1] field with a soft catalogue-flank ramp. To keep the two H8 lines distinct, its receipts live under <code>h8asa-*</code>.</p>
<div class="download"><a class="button" href="downloads/gemsdoe40-h8-asa-spi-depthkde-20261006T035031Z-b845d3ad449e-zeros.zip" download>Download H8-ASA portal-safe GeoTIFF (.zip) <span aria-hidden="true">↓</span></a><a class="button" href="downloads/gemsdoe40-h8-asa-spi-depthkde-20261006T035031Z-b845d3ad449e-nan.tif" download>NaN-outside research .tif <span aria-hidden="true">↓</span></a></div>
<p class="file-details">3.60 MB · single-band float32 · EPSG:32611 · 3,730 × 3,292 · 100 m · all values in [0,1]<br>Name: GEMSDOE40-H8-ASA-SPI-b845d3ad449e · sha256 b00328ce401cf5be… (full hashes in <a href="data/h8asa-validation.json">validation</a> / <a href="data/current-candidate.json">manifest</a>)</p>
<div class="tablewrap"><table><thead><tr><th>H8-ASA measurement</th><th>Result</th></tr></thead><tbody>
<tr><td>Synthetic suite S1–S5 (before scoring)</td><td class="num">PASS (10 tests)</td></tr>
<tr><td>Novelty vs 343 prior artifacts</td><td class="num">PASS — max |Pearson| 0.2528, Jaccard 0.1121, containment 0.2016</td></tr>
<tr><td>Registered gate: pooled proxy DTI &gt; 0.091550</td><td class="num">FAIL — 0.024128</td></tr>
<tr><td>Registered gate: ≥10/16 block wins</td><td class="num">FAIL — 1/16</td></tr>
<tr><td>Independent byte reproduction (all 4 artifacts)</td><td class="num">PASS</td></tr></tbody></table></div>
<p class="micro">HOLD — DO NOT SUBMIT H8-ASA. Diagnosis: 155k confidence units pay false-positive cost far from truth (TP_w ≈ 2,205 vs FP_w ≈ 145,742 on the proxy), and the registered catalogue-flank ramp removes mass where the catalogue-like proxy lives. <a href="research/h8asa-preregistration-20261006.md">Preregistration + amendments</a> · <a href="reports/h8-review-20261006.md">three-pass review</a> · <a href="downloads/gemsdoe40-h8-asa-spi-depthkde-20261006T035031Z-b845d3ad449e-cloud.csv.gz">depth-cell cloud (CSV.gz)</a></p></section>'''
    h8asa_exec = '''<section class="section" id="h8asa"><p class="eyebrow">CONCURRENT SESSION / H8-ASA ANALYTIC SIGNAL</p><h2>A second held artifact, kept distinct.</h2><div class="twocol"><div><span class="tag hold">HOLD — DO NOT SUBMIT</span><div class="download"><a class="button" href="downloads/gemsdoe40-h8-asa-spi-depthkde-20261006T035031Z-b845d3ad449e-zeros.zip" download>H8-ASA portal-safe .zip <span aria-hidden="true">↓</span></a><a class="button" href="downloads/gemsdoe40-h8-asa-spi-depthkde-20261006T035031Z-b845d3ad449e-nan.tif" download>NaN-outside research .tif <span aria-hidden="true">↓</span></a></div><h3>Unique submission name</h3><div class="codebox" id="h8asa-name">GEMSDOE40-H8-ASA-SPI-b845d3ad449e</div><button class="copy" data-copy="h8asa-name">Copy name</button><h3>Short note · 152 characters</h3><div class="codebox" id="h8asa-note">GEMSDOE40 H8 | analytic-signal local-wavenumber depth cells x H4-Euler corroboration; soft catalogue ramp; continuous [0,1]; HOLD: gate failed; unscored</div><button class="copy" data-copy="h8asa-note">Copy note</button></div>
<div class="callout"><p class="eyebrow">WHY IT IS HELD</p><h3>Novel and valid; the gate failed.</h3><p>H8-ASA (tapered-FFT analytic signal, contact depth z=√(A/|λ_min|), H4-Euler corroboration, σ=2 KDE, flank ramp) passed synthetic S1–S5, format, and the 343-artifact novelty audit (max |Pearson| 0.2528). Its registered gate failed: pooled proxy DTI 0.024128 &lt; 0.091550; block wins 1/16 &lt; 10. Independent re-run reproduced all four artifacts byte-for-byte.</p><a href="reports/h8-results-20261006.md">H8-ASA result ↗</a> · <a href="research/h8asa-preregistration-20261006.md">preregistration ↗</a></div></div></section>
'''
    h8asa_hyp = '''<section class="section prose"><h2>Concurrent dual registration — same day, two slates, one naming collision</h2>
<p>On 2026-10-06 two independent sessions each registered an "H8–H12" slate before implementation. Session 2’s slate (above: trace-locked Euler H8, crest emission H13, seismic corridor H11, ComCat H12) is preserved in <a href="research/h8-preregistration-20261006.md">h8-preregistration-20261006.md</a>. The concurrent session’s slate — <strong>H8 analytic-signal local-wavenumber depth cells (implemented, HOLD at its gate)</strong>, H9 gravity basin-margin ridges, H10 multi-scale ridge persistence, H11 Werner deconvolution, H12 DTI marginal-bar reallocation (rejected as primary) — is preserved in <a href="research/h8asa-preregistration-20261006.md">h8asa-preregistration-20261006.md</a>, and its artifact/receipts carry the <code>h8asa</code> prefix to stay distinct. Neither slate is a duplicate of the other; the collision is disclosed, not silently merged.</p>
<p>H8-ASA measured: synthetic S1–S5 PASS; novelty PASS (max |Pearson| 0.2528 vs 343 priors); gate FAIL (pooled proxy 0.024128 &lt; 0.091550; block wins 1/16); byte-identical independent reproduction. <a href="reports/h8-results-20261006.md">Result</a> · <a href="reports/h8-review-20261006.md">three-pass review</a>.</p></section>'''


    body = f'''<section class="hero"><div><p class="kicker">SESSION 2 / EXPERIMENTS H8 + H13 / GEODAWN, NEVADA / 06 OCT 2026</p>
<h1>Depth consensus,<br>locked to <em>traces.</em></h1><p class="lead">Two new fault-confidence rasters from Euler source depths: a trace-locked continuous field (H8) and its value-concentrated crest emission (H13). Audited against all 343 prior artifacts and honestly gated.</p>
{hold}<div class="download">{download}</div><p class="file-details">363 KB · single-band float32 · EPSG:32611<br>100 m · 3,730 rows × 3,292 columns · values in [0, 1]<br>NaN only outside the sample footprint</p>
<p class="file-details"><a href="{h8link}" download>Download the H8 continuous sibling (1.48 MB) ↓</a></p>
<div class="notice"><strong>Two new files. Neither is a proven improvement.</strong><p>Both pass format and full-corpus novelty. Both fail the off-catalogue proxy holdout — but both beat H33-B2 ~6× on the repaired catalogue-component holdout, the first non-circular skill signal for the Euler family. Research downloads; do not spend a weekly slot.</p></div>
<div class="actions"><a class="textlink" href="executive-summary.html">File, name &amp; submission guide ↗</a><a class="textlink" href="evidence.html">Inspect the evidence ↗</a></div>
</div><div class="map-panel"><a href="assets/h13-raster.png"><img src="assets/h13-raster.png" alt="Actual H13 binary Euler depth-consensus crest raster on the GeoDAWN footprint, UTM zone 11N" width="1005" height="1185"></a><div class="map-foot"><span>MODEL OUTPUT / NOT OBSERVED FAULTS</span><b>OPEN MAP ↗</b></div></div></section>
<div class="checkstrip"><div><span class="stat">21,041</span><span class="label">Depth-consensus crests emitted</span></div><div><span class="stat">{h13u['inventory_blobs']}</span><span class="label">Prior artifacts audited</span></div><div><span class="stat">{h13u['max_abs_pearson']:.4f}</span><span class="label">Largest raw |correlation|</span></div><div><span class="stat">0</span><span class="label">Competition slots used</span></div></div>
<section class="section" id="research"><div class="sectionhead"><div><p class="eyebrow">01 / FROM DEPTH CLOUD TO TRACE</p><h2>What changed from H4.</h2></div><a href="methodology.html">Full pipeline ↗</a></div>
<div class="grid3"><article class="card"><span class="stepnum">01 — REUSE FROZEN PHYSICS</span><h3>The H4 solution cloud.</h3><p>46,656 QC-passed SI=0 contact solutions (offset A fitted) from TMI and gravity dG/dz; 20,617 carry cluster weights. Hash-pinned, never re-tuned.</p></article>
<article class="card"><span class="stepnum">02 — LOCK TO TRACES</span><h3>Orientation-NMS crests.</h3><p>A structure tensor orients the consensus field; crests survive only where ≥3 corridor solutions agree within 445 m of depth standard deviation along ±800 m of strike. 73.5 % of crests pass; median depth 770 m.</p></article>
<article class="card"><span class="stepnum">03 — CONCENTRATE VALUE</span><h3>H13 spends mass where credit is.</h3><p>The metric charges 0.2·p(x) and pays ≤p(x)·k(d) — both linear in stored value. H13 emits 1.0 on consensus crests only: 5.8× the proxy DTI of the diluted H8 field, still below the gate.</p></article></div></section>
<section class="section" id="decision"><div class="sectionhead"><div><p class="eyebrow">02 / THE RESULT, WITHOUT THE SPIN</p><h2>Novelty and format pass. The proxy gate does not.</h2></div><a href="evidence.html">All checks &amp; limitations ↗</a></div>{results_table}
<p class="micro">Owner-derived SGMC proxy diagnostics, not organizer scores. CAT-HID was repaired this session (two latent defects made every historical reading zero); all candidates and baselines were re-measured under the repaired instrument.</p></section>
<section class="section twocol"><div class="callout"><p class="eyebrow">03 / WHY THE PREVIOUS BEST HELPED</p><h3>Fewer predictions.<br>Not more discovered faults.</h3><p>Byte-exact comparison proves H33-B2 is the 40,199-pixel reference with 2,545 catalogue-adjacent pixels removed. At DTI 0.2778 the metric lets you trade up to 0.0588 TP credit per FP unit saved (~17:1).</p><a class="textlink" href="leaderboard-analysis.html">What 0.2778 does—and doesn’t—tell us ↗</a></div>
<div class="callout" id="feed"><p class="eyebrow">04 / KEEP THE RECORD CURRENT</p><h3>An official-source feed,<br>not a submission bot.</h3><p id="feed-status" aria-live="polite">Loading the dated USGS context snapshot…</p><ul id="feed-events" class="eventlist"></ul><a class="textlink" href="sources.html#context">Sources, freshness &amp; access limits ↗</a></div></section>
<section class="section"><div class="reportline"><span>Official leaderboard observed 6 October: <strong>{official['top_rows'][0]['score']:.4f}</strong> at #1. Not a live scrape.</span><a href="{BOARD}">Open official board ↗</a></div><div class="reportline"><span>All {projects['project_count']} brief-listed projects; {projects['reported_score_count']} owner-reported scores; {len(inv['repository_snapshots'])} repositories inventoried.</span><a href="leaderboard.html">Complete project register ↗</a></div></section>'''
    page("index.html", "Depth consensus, locked to traces", body + h8asa_index + parallel, "index.html")

    guide = subhero("EXECUTIVE SUMMARY / DOWNLOAD & DECISION", "Two files. One clear decision.", "Both session-2 TIFFs are submission-format valid and genuinely distinct from all 343 inventoried prior outputs. Neither has earned a competition slot.")
    guide += f'''<section class="section"><div class="twocol"><div>{hold}<div class="download">{download}</div><p class="micro">Download the .tif itself — not this web page, a report, or a preview image.</p><h3>Exact filename</h3><div class="codebox" id="filename">{esc(c['filename'])}</div><button class="copy" data-copy="filename">Copy filename</button><h3>Tracking name</h3><div class="codebox" id="submission-name">{esc(c['name'])}</div><button class="copy" data-copy="submission-name">Copy name</button></div>
<div class="callout"><p class="eyebrow">CURRENT DECISION</p><h3>Do not upload either version.</h3><p>H13’s proxy DTI {g13['g3_detail']['candidate_pooled_dti']:.6f} (H8: {g8['g3_detail']['candidate_pooled_dti']:.6f}) is below H33-B2’s {g13['g3_detail']['h33b2_pooled_dti']:.6f} on the same frozen instrument, and below the frozen gate bar. No organizer score exists. No submission has been made.</p><p>The brief’s own rule is retained: never spend a weekly slot on an idea that hasn’t beaten the current holdout best. A valid file is not a recommended one.</p><a href="evidence.html">Read the measured result ↗</a></div></div>
<h3>Short note · {c['note_characters']} characters · research record only</h3><div class="codebox" id="submission-note">{esc(c['note'])}</div><button class="copy" data-copy="submission-note">Copy note</button>
<h3>SHA-256 of the actual downloads</h3><div class="codebox" id="file-sha">{c['sha256']}</div><button class="copy" data-copy="file-sha">Copy H13 SHA-256</button><p class="micro">H8 sibling: <span class="mono">{esc(c['sibling_candidate']['filename'])}</span> · SHA-256 <span class="mono">{esc(c['sibling_candidate']['sha256'])}</span> · <a href="{h8link}" download>Download H8</a></p><p class="micro"><a href="data/h13-format.json">H13 format receipt</a> · <a href="data/h13-uniqueness.json">H13 raw-output comparisons</a> · <a href="downloads/h13-submission-note.txt">Name and note as text</a></p></section>
<section class="section prose"><h2>How a future approved submission is entered</h2><p><strong>These are future instructions, not permission to submit H8/H13.</strong> First require a reproducible gate win on a registered, source-independent protocol, plus complete novelty and format passes.</p>
<ol><li>Open the <a href="{PROBLEM}">official competition</a> in your own account. Confirm eligibility, enrollment and current rules. Never put passwords or tokens in this repository.</li><li>Download the exact approved <strong>.tif</strong> from the prominent button. Compare its SHA-256 with its receipt. Do not upload an HTML file saved by the browser.</li><li>Open <strong>New submission</strong>. In <strong>File to submit</strong>, choose the downloaded GeoTIFF. A ZIP containing exactly one GeoTIFF is also accepted; this project supplies the TIFF directly.</li><li>Paste the approved short note into <strong>Note (optional)</strong>. Keep the unique tracking name and full SHA-256 in the local experiment record.</li><li>Submit, then save the server’s validation response and any file-level score receipt. An account’s best leaderboard row is not a receipt for a particular file.</li><li>Respect the <a href="{RULES}">three-per-week limit</a>. Choose one final submission for both prize rounds. This repository never performs a DrivenData upload.</li></ol>
<h2>Preventing “Predicted values must be in range [0, 1]”</h2><p>Both written files were reopened from disk and re-checked across <strong>all 5,167,373 inside-footprint pixels</strong>: every value is finite and in [0, 1] (H13 stores exactly 0.0/1.0; H8 is continuous). All 7,111,787 outside pixels are NaN, matching the sample mask, and the feature stack’s −3.4028235e38 sentinel is never copied into predictions.</p><p>NaN outside the footprint is the documented sample contract. We do not claim NaN itself causes rejection and do not silently swap zeros for it; a local pass is not a guarantee about the server-side validator. If an authorized upload ever fails, retain the exact bytes and error text for diagnosis.</p>
<h2>Rebuild, don’t rename an old TIFF</h2><div class="codebox code">python3 -m venv .venv
. .venv/bin/activate
python -m pip install -r requirements-research.txt
python -m pip install -e .
bash scripts/download_competition_data.sh
python scripts/fetch_prior_cache.py --inventory docs/data/prior-inventory-20261006.json --cache data/prior
python scripts/run_trace_locked_euler.py        # H8 continuous field
python scripts/run_crest_emission.py            # H13 crest-binary
python scripts/audit_trace_candidate.py --work work/h13
python scripts/build_site.py --check</div><p>CPU-only. The 419 MB feature stack, template, labels, frozen proxy and 343-artifact prior corpus are restored automatically from pinned public mirrors; no GPU or trained network is required. Source links and mirror-provenance limits are in the <a href="sources.html">research library</a>.</p>
<p><a href="https://github.com/buffedlizard55-lab/GEMSDOE40/actions/workflows/reproduce.yml">Reproduction workflow ↗</a> · <a href="downloads/h4-euler-solutions.csv.gz">Download all 46,656 QC-passing depth solutions (CSV.gz)</a></p><p class="micro">Historical status: HOLD — DO NOT SUBMIT H2-B, H4, H7, H40. Archived files remain for learning and are not the current downloads.</p></section>'''
    page("executive-summary.html", "Executive summary and submission guide", guide + h8asa_exec + parallel, "executive-summary.html")

    closest = "".join(f'<tr><td>{esc(r["artifact"]["repo"])}<br><span class="mono">{esc(Path(r["artifact"]["path"]).name)}</span></td><td class="num">{r["pearson_r"]:.6f}</td><td class="num">{r["top_jaccard"]:.6f}</td></tr>' for r in h13u["closest_by_pearson"])
    evidence = subhero("AUDIT / NO SELECTIVE REPORTING", "Evidence you can inspect.", "Hashes prove artifact identity. Frozen gates decide promotion. A proxy test measures a limited outcome. None of these alone establishes a new fault or a leaderboard win.")
    evidence += f'''<section class="section">{results_table}<div class="notice"><strong>Why both candidates are HOLD.</strong><p>G3 is the binding gate: pooled DTI on the frozen SGMC proxy (4×6 blocks, 3-cell guard, exact-label zeroing) must exceed 0.091550 — H33-B2 measured on the identical instrument — and the controls. H13 reaches {g13['g3_detail']['candidate_pooled_dti']:.6f}, H8 {g8['g3_detail']['candidate_pooled_dti']:.6f}. Both fall below the mass-matched random controls ({g13['g3_detail']['best_random_control_dti']:.6f} / {g8['g3_detail']['best_random_control_dti']:.6f}), which says Euler crests are not preferentially located on off-catalogue SGMC traces — consistent with session 1’s AUC 0.534 finding. The SGMC-derived incumbent’s 0.835907 shows the proxy’s ceiling belongs to SGMC-matching fields; it is circular and is not a target.</p><p>Counter-signal, honestly: on the repaired, non-circular catalogue-component holdout, H8 ({g8['g4_detail']['candidate_cat_hidden_mean']:.6f}) and H13 ({g13['g4_detail']['candidate_cat_hidden_mean']:.6f}) beat H33-B2 ({g13['g4_detail']['h33b2_cat_hidden_mean']:.6f}) ~6×. The Euler family has fault-finding skill; its placement does not match the SGMC proxy. Placement against the hidden test set cannot be measured locally.</p></div>
<div class="grid3"><div class="card"><span class="tag pass">Format pass ×2</span><h3>Exact template contract.</h3><p>One float32 band each. EPSG:32611, 100 m, 3,730 × 3,292. Exact affine transform and footprint. Finite [0,1] inside; NaN only outside.</p><a href="data/h13-format.json">H13 receipt ↗</a> · <a href="data/h8-format.json">H8 receipt ↗</a></div>
<div class="card"><span class="tag pass">Uniqueness pass ×2</span><h3>Raw values, not previews.</h3><p>{h13u['inventory_blobs']} byte-verified artifacts each; full-size array comparisons for both candidates. Max |Pearson| {h13u['max_abs_pearson']:.4f} (H13) / {h8u['max_abs_pearson']:.4f} (H8); zero near-duplicates under both the H4 and historic H2-B rules.</p><a href="data/h13-uniqueness.json">H13 comparisons ↗</a></div>
<div class="card"><span class="tag hold">Promotion fail ×2</span><h3>No weekly slot.</h3><p>G3 failed for both; gates were frozen before scoring and not relaxed. The CAT-HID win (G4) is reported as a skill signal, not as an override.</p><a href="data/h13-validation.json">H13 gate record ↗</a></div></div></section>
<section class="section"><div class="sectionhead"><div><p class="eyebrow">NOVELTY / FULL CORPUS, BOTH CANDIDATES</p><h2>Not a re-packaged previous submission.</h2></div></div><p class="soft">Reject identical file or canonical pixel hashes, |Pearson| ≥0.85, top-37,654 positive-cell Jaccard ≥0.50, or containment ≥0.80. All pixels compared — no random sampling.</p>
<div class="tablewrap"><table><thead><tr><th>Closest prior outputs to H13 by |r|</th><th>Pearson r</th><th>Top-budget Jaccard</th></tr></thead><tbody>{closest}</tbody></table></div><p class="micro">H13 maxima: |r| {h13u['max_abs_pearson']:.6f}, Jaccard {h13u['max_top_jaccard']:.6f}, containment {h13u['max_top_containment']:.6f}. H8 maxima: |r| {h8u['max_abs_pearson']:.6f}, Jaccard {h8u['max_top_jaccard']:.6f}, containment {h8u['max_top_containment']:.6f}. Corpus scope: {len(inv['repository_snapshots'])} repositories, {inv['history_expansion']['public_branch_heads']:,} pinned branch heads, {inv['history_expansion']['reachable_commits']:,} reachable commits, {len(inv['zip_archives_checked'])} ZIP paths inspected.</p><div class="twocol comparison"><figure><a href="assets/h13-raster.png"><img loading="lazy" src="assets/h13-raster.png" alt="H13 binary crest emission preview"></a><figcaption>H13: binary depth-consensus crests (21,041 px).</figcaption></figure><figure><a href="assets/h8-raster.png"><img loading="lazy" src="assets/h8-raster.png" alt="H8 trace-locked KDE preview"></a><figcaption>H8: continuous trace-locked depth-KDE. Same 0–1 color range; 4×4 max pooling for visibility; TIFFs unmodified.</figcaption></figure></div></section>
<section class="section prose"><h2>Instrument repair disclosed</h2><p>The conventional catalogue-component holdout (CAT-HID) had two latent defects repaired this session: the hidden components were included in their own exclusion flank (truth collapsed to zero), and the 20 % hide fraction counted background pixels (selecting all components). Every historical CAT-HID number in this repository was a zero from these defects; none ever drove a decision. All session-2 comparisons re-measure every candidate and baseline under the repaired instrument.</p>
<h2>What cannot be claimed</h2><ul><li>No independently verified unknown-fault truth set or competition score for H8/H13.</li><li>No proof that a modeled contact is a fault, geothermal vent, fluid conduit, or viable reservoir.</li><li>No organizer authentication of the public mirrors; hashes prove consistency, not provenance.</li><li>No claim that proxy performance transfers to the hidden test set — the session’s own controls show it need not.</li></ul>
<p><a href="data/h13-generation.json">H13 configuration/code hashes</a> · <a href="data/h8-generation.json">H8 configuration/code hashes</a> · <a href="research/h8-preregistration-20261006.md">Frozen registration + amendments</a> · <a href="reports/session2-results-20261006.md">Human-readable result</a></p></section>'''
    page("evidence.html", "Evidence and validation", evidence, "evidence.html")

    hypotheses = subhero("RESEARCH / REGISTER BEFORE IMPLEMENTATION", "Five new hypotheses.<br>Two frozen experiments. One frozen pre-screen.", "Ranked by expected DTI improvement per unit cost before implementation. H8 and H13 were implemented; H9 and H10 were frozen-pre-screened and rejected; H11–H12 remain registered. The earlier H4–H7 slate is preserved in the session-1 registration.")
    hypotheses += '''<section class="section"><div class="tablewrap"><table><thead><tr><th>Rank / hypothesis</th><th>Layers and physical signature</th><th>Off-catalogue rationale &amp; difference</th><th>Status / cost</th></tr></thead><tbody>
<tr><td><strong>1 · H8</strong><br>Trace-locked Euler depth consensus</td><td>H4 cloud (TMI + gravity dG/dz, SI=0+A); orientation-NMS crests with along-strike depth-consensus corridors.</td><td>Continuation strands and concealed extensions keep coherent 3-D source geometry that edge maps discard. No repo arm or corpus artifact applied orientation-NMS trace locking to an Euler cloud.</td><td><strong>Implemented; HOLD</strong> (G3 fail, G4 win). Medium cost.</td></tr>
<tr><td><strong>1.5 · H13</strong><br>Value-concentrated crest emission</td><td>Identical H8 physics; binary 1.0 emission on consensus crests (metric linearity argument, registered before scoring).</td><td>Tests the diagnosed mass-dilution failure at zero new degrees of freedom. Distinct emission from every corpus artifact.</td><td><strong>Implemented; HOLD</strong> (G3 fail, G4 win). Minutes.</td></tr>
<tr><td><strong>2 · H9</strong><br>Blind basement-flexure faults</td><td><span class="mono">depth_to_base_surf</span> (15), <span class="mono">cond_surf</span> (17), <span class="mono">iso_grav_anom_hg</span> (18), <span class="mono">det_elev</span> (12).</td><td>A basement flexure ridge with a conductivity break and gravity-gradient ridge marks buried normal faults — the class surface compilations least contain. Bands 15/17 never used by any arm.</td><td><strong>Pre-screened 2026-10-06: NEGATIVE.</strong> Best indicator (HG of det_elev) 0.1048 vs its own mass-matched random control 0.1158 — no placement skill beyond random mass. <a href="data/h9-prescore.json">Receipt</a>.</td></tr>
<tr><td><strong>3 · H10</strong><br>Geodetic strain-rate lineaments</td><td><span class="mono">geod_shearrate</span> (7), <span class="mono">geod_dilaterate</span> (8), <span class="mono">geod_2ndinv</span> (4).</td><td>Localized interseismic strain marks actively slipping strands missing from static compilations; relay segments between catalogue traces.</td><td><strong>Pre-screened 2026-10-06: NEGATIVE.</strong> Best indicator (HG of geod_dilaterate) 0.0701 vs its own mass-matched random control 0.1158; the registered structure-tensor lineament detector scored 0.0653. <a href="data/h10-prescore.json">Receipt</a>.</td></tr>
<tr><td><strong>4 · H11</strong><br>Seismic corridor × Euler intersection</td><td><span class="mono">deq_n100a15</span> (10), <span class="mono">ieq_n100a15</span> (16), Euler support.</td><td>Simultaneous proximity to recorded seismicity and shallow depth-consistent Euler support marks active unmapped strands.</td><td>Registered. Low–medium cost.</td></tr>
<tr><td><strong>5 · H12</strong><br>ComCat focal-mechanism fields</td><td>USGS ComCat FDSN event service + event layers.</td><td>Nodal-plane orientations sharpen active-fault geometry beyond smooth density bands.</td><td><strong>Blocked</strong>: sandbox egress; needs unrestricted runner. Free official source named.</td></tr></tbody></table></div>
<p class="micro">Session-1 slate (H4 offset-aware Euler, H5 finite-step, H6 plane geometry, H7 representation stability) is preserved in <a href="research/preregistered-hypotheses-20261006.md">its registration</a>; H4 was implemented and held. The numbered H4-A…H4-F arms are documented in <a href="research/hypotheses.md">the append-only register</a>.</p></section>'''
    hypotheses += '''<section class="section prose"><h2>H9 frozen pre-screen result (2026-10-06)</h2><p>The H9 pre-screen protocol was appended to the preregistration <em>before</em> any H9 scoring (<a href="research/h8-preregistration-20261006.md">addendum 2</a>; protocol pinned at sha256 <span class="mono">95ef16f1…</span>). Six frozen indicators on bands 12/15/17/18 were percentile-emitted and scored on the frozen SGMC proxy alongside the audit's exact mass-matched controls. The frozen decision rule required the best indicator to beat BOTH 0.039354 (2 × H13's G3 score) AND 2 × its own random control.</p><div class="tablewrap"><table><thead><tr><th>Indicator</th><th>Proxy score</th><th>Random control</th><th>Gradient-topK</th></tr></thead><tbody><tr><td>HG_det_elev (best)</td><td><strong>0.1048</strong></td><td>0.1158</td><td>0.0800</td></tr><tr><td>HG_cond</td><td>0.0710</td><td>0.1158</td><td>0.0800</td></tr><tr><td>HG_grav_hg</td><td>0.0680</td><td>0.1158</td><td>0.0800</td></tr><tr><td>step_depth_base</td><td>0.0650</td><td>0.1156</td><td>0.0800</td></tr><tr><td>flexure_product</td><td>0.0619</td><td>0.1158</td><td>0.0800</td></tr><tr><td>HG_depth_base</td><td>0.0579</td><td>0.1158</td><td>0.0800</td></tr></tbody></table></div><p class="micro">Decision: <strong>NEGATIVE-AT-PRESCREEN</strong>; no H9 implementation compute will be spent. The three subsurface bands central to H9 (15/17/18) rank at the bottom; only the detrended-elevation gradient (band 12) comes near the random level, and still below it. At dense emission mass (~2.6 M value-budget), random dots reach 0.1158 on this proxy — consistent with the session-2 finding that the proxy rewards diffuse mass rather than placement. Full numbers: <a href="data/h9-prescore.json">docs/data/h9-prescore.json</a>; report: <a href="reports/session3-h9-prescore-20261006.md">session-3 pre-screen report</a>.</p></section>'''
    hypotheses += '''<section class="section prose"><h2>H10 frozen pre-screen result (2026-10-06)</h2><p>H10 (geodetic strain-rate lineaments on bands 4/7/8) followed the same registered fail-fast pattern (<a href="research/h8-preregistration-20261006.md">addendum 3</a>, pinned at sha256 <span class="mono">d495fc0f…</span> before scoring). Six frozen indicators — gradient magnitudes of each band, band 4 used directly, the registered oriented structure-tensor linearity of band 7, and the HG(7) × HG(8) rank product — were percentile-emitted and scored against the audit's exact mass-matched controls.</p><div class="tablewrap"><table><thead><tr><th>Indicator</th><th>Proxy score</th><th>Random control</th><th>Gradient-topK</th></tr></thead><tbody><tr><td>HG_dilate (best)</td><td><strong>0.0701</strong></td><td>0.1158</td><td>0.0800</td></tr><tr><td>HG_2ndinv</td><td>0.0690</td><td>0.1158</td><td>0.0800</td></tr><tr><td>inv_direct</td><td>0.0675</td><td>0.1156</td><td>0.0800</td></tr><tr><td>shear_x_dilate</td><td>0.0668</td><td>0.1158</td><td>0.0800</td></tr><tr><td>lineament_shear</td><td>0.0653</td><td>0.1156</td><td>0.0800</td></tr><tr><td>HG_shear</td><td>0.0647</td><td>0.1158</td><td>0.0800</td></tr></tbody></table></div><p class="micro">Decision: <strong>NEGATIVE-AT-PRESCREEN</strong>; no H10 implementation compute will be spent. With H9 also closed, every registered new-band-family lever has failed the proxy placement test; the dense-mass random level ≈ 0.1157 reproduced exactly across both pre-screens. Full numbers: <a href="data/h10-prescore.json">docs/data/h10-prescore.json</a>; report: <a href="reports/session3-h10-prescore-20261006.md">session-3 H10 pre-screen report</a>.</p></section>'''
    hypotheses += '''<section class="section prose"><h2>Validation instruments in force</h2><p>G3 uses the frozen SGMC-derived proxy (26d142…) — a diagnostic whose ceiling belongs to SGMC-matching fields. G4 (CAT-HID, repaired 2026-10-06) is the non-circular skill check: 20 % of catalogue components hidden and scored in eroded quadrants. The LM live-mirror is reported as diagnostic only (circular incumbent). A future promotion protocol must be source-independent — registered before scoring — before any slot is spent.</p></section>'''
    hypotheses += h8asa_hyp
    page("hypotheses.html", "Ranked hypotheses", hypotheses, "hypotheses.html")

    method = subhero("METHOD / SESSION 2 PIPELINE", "Euler depths → trace consensus → map.", "Every stage frozen before scoring. The solver settings are session 1’s H4 settings; session 2 changed only the emission geometry.")
    method += '''<section class="section prose"><ol><li><strong>Input cloud (frozen H4).</strong> Reid SI=0 contact equation with arbitrary offset A on TMI (200 m continuation) and gravity dG/dz (top-edge approximation), 10–51 px windows, stride 5; QC by condition number, relative residual, depth 100–8,000 m, offset and depth-se gates; 3-D cluster weights penalizing depth, scatter and cross-window inconsistency. 46,656 records; 20,617 weighted.</li>
<li><strong>Per-family KDE.</strong> Bilinear splat of weighted points, Gaussian σ=2, truncate 4, 99.5-percentile normalization.</li>
<li><strong>Consensus field.</strong> C = (M + G + √(MG))/3 — cross-family corroboration; exact known pixels zeroed.</li>
<li><strong>Orientation.</strong> Structure tensor (inner σ=1, integration σ=3); isotropy floor 0.15; gradient direction quantized to four bins.</li>
<li><strong>Orientation NMS.</strong> Crests are one-sided-tie local maxima along the quantized gradient direction — plateaus thin to 1-px ridges. 28,646 crest cells.</li>
<li><strong>Along-strike depth consensus.</strong> Oriented corridor (±800 m strike × ±300 m across): raw count ≥3 and cluster-weight-weighted depth SD ≤445 m. 21,041 cells pass (73.5 %); median depth 770 m; median SD 121 m.</li>
<li><strong>Emission.</strong> H8: continuous gaussian(C·γ, σ=1) normalized to [0,1]. H13: binary 1.0 on passing crests. Exact known pixels zeroed; NaN outside the sample footprint.</li></ol>
<h2>Assumptions and limits</h2><ul><li>Effective depths are relative to a reference observation plane, not verified ground depths (draped survey datum unverified).</li><li>Gravity SI=0 on dG/dz is a local top-edge approximation, not a finite-step inversion (Reid &amp; Thurston 2014).</li><li>A potential-field contact is not automatically a fault; lithologic boundaries and intrusions are confounders.</li><li>The corridor SD gate uses cluster-weight-weighted moments (pre-scoring correction registered in the preregistration).</li></ul>
<p><a href="research/h8-preregistration-20261006.md">Frozen constants and amendments ↗</a> · <a href="https://doi.org/10.1190/1.1442774">Reid et al. 1990 ↗</a> · <a href="https://www.reid-geophys.co.uk/wp-content/uploads/2017/11/Reid-Thurston-2014.pdf">Reid &amp; Thurston 2014 ↗</a></p></section>'''
    page("methodology.html", "Euler method", method, "hypotheses.html")

    analysis = subhero("LEADERBOARD ANALYSIS / MEASURED, NOT SPECULATED", "Why 0.2778 happened.", "Byte-exact set comparison plus the metric’s own marginal economics. The score attribution itself remains owner-reported.")
    analysis += f'''<section class="section prose"><h2>The measured facts</h2><ul><li>H33-B2 is <strong>exactly</strong> H27-4 (40,199 px) minus the 2,545 pixels at ≤200 m from the catalogue; it adds zero pixels (<a href="data/h33-measured-analysis.json">measured JSON</a>).</li><li>DTI = T/(0.2T + 0.2FP + 0.8G). A removal losing L of TP credit and saving S of FP mass helps iff (1−0.2D)·L &lt; 0.2D·S. At D=0.2778 the bound is 0.05883 TP credit per FP unit (~17:1).</li><li>The owner reports 0.2708 → 0.2778 for this prune; the leaderboard does not identify TIFFs, so the pairing stays unauthenticated.</li><li>Session-2 measurements on local instruments: H13 CAT-HID {g13['g4_detail']['candidate_cat_hidden_mean']:.6f}, H8 {g8['g4_detail']['candidate_cat_hidden_mean']:.6f}, H33-B2 {g13['g4_detail']['h33b2_cat_hidden_mean']:.6f}; proxy pooled DTI H33-B2 {g13['g3_detail']['h33b2_pooled_dti']:.6f}.</li></ul>
<h2>What could beat it (hypotheses, not forecasts)</h2><ol><li><strong>More placement, same budget.</strong> Live gains in the 0.24–0.28 family came from pruning and trace arrangement, not new physics. Placing mass on actual hidden-trace geometry is the lever — unmeasurable locally, so the next session targets blind-fault physics (H9) where placement evidence is independent of the catalogue.</li><li><strong>Concentrate value.</strong> H13’s 5.8× over H8 shows emission form matters; a future candidate should never max-normalize diluted flanks.</li><li><strong>Corroborate before emitting.</strong> Each additional independent family (gravity, geodetic, seismic, basement depth) that must agree shrinks the false-positive class the metric charges.</li><li><strong>Keep mass near the working budget.</strong> 21–44k positive pixels with trace-like arrangement; diffuse fields over 100k px have never scored above 0.19 live in the corpus.</li></ol><p>None of this is a score forecast. <a href="https://www.drivendata.org/competitions/306/competition-doe-gems/leaderboard/">Official board ↗</a> · <a href="data/h33-measured-analysis.json">Measured analysis JSON ↗</a></p></section>'''
    page("leaderboard-analysis.html", "Understanding the 0.2778 reference", analysis, "evidence.html")

    rows = []
    for project in projects["projects"]:
        subs = project["submissions"]
        details = "<ul class=\"submissions\">" + "".join(f'<li>{esc(s["name"])}<br><strong>{s["score"]:.4f}</strong> · owner report</li>' if s['score'] is not None else f'<li>{esc(s["name"])}<br>Score not supplied</li>' for s in subs) + "</ul>" if subs else "No submission/score supplied in brief."
        source = project.get("page_source", {})
        source_link = f'<a href="{esc(source.get("url", project["site"]))}">Pinned page source ↗</a>'
        rows.append(f'<tr data-project-row><td><a href="{esc(project["site"])}"><strong>{esc(project["repo"])}</strong></a></td><td>{details}</td><td class="num">{project["audited_unique_tiff_blobs"]}</td><td>{source_link}<br><span class="micro">{esc(source.get("commit", "")[:10])}</span></td></tr>')
    history = subhero("COMPLETE REGISTER / ALL BRIEF-LISTED PROJECTS", "Keep the claims<br>and the evidence separate.", f"{projects['project_count']} projects, {projects['reported_score_count']} supplied scores. Null scores remain unknown. Page source was read at pinned GitHub revisions; this is not a live-site uptime claim or an organizer receipt.")
    history += f'''<section class="section"><div class="notice"><strong>Last official observation: {official['top_rows'][0]['score']:.4f} leading, 6 October 2026.</strong><p>0.2778 appears as an account-level public score. The association with H33-B2 below is the owner’s report, not independently proved by that leaderboard row. No scheduled DrivenData scrape is running.</p></div><label for="project-search" class="label">Filter projects, filenames or reported scores</label><br><input class="search" id="project-search" type="search" placeholder="e.g. 0.2778, Euler, GEMSDOE32"><p class="micro" id="search-count" aria-live="polite">{projects['project_count']} project rows shown</p>
<div class="tablewrap"><table class="scorelist"><thead><tr><th>Project / site</th><th>Submission and owner-reported score</th><th>Audited TIFF blobs</th><th>Source review</th></tr></thead><tbody>{''.join(rows)}</tbody></table></div><p class="micro">Counts include historical and experimental outputs, not only competition submissions. A shared blob may appear under multiple projects. The broader raw-output census spans {len(inv['repository_snapshots'])} repositories and {inv['unique_git_blobs']} distinct TIFF-named artifacts.</p><div class="linkrow"><a href="data/project-site-review-20261006.json">Complete page/score JSON</a><a href="data/prior-inventory-20261006.json">Immutable artifact inventory</a><a href="data/official-observation-20261006.json">Dated board observation</a></div></section>'''
    page("leaderboard.html", "Complete project and score register", history, "evidence.html")

    source_rows = [
        ("Official competition", "Task, metric and format", PROBLEM, "Geological fault confidence, not vent detection. 300 m distance-weighted Tversky; exact raster requirements."),
        ("Official rules", "DOE / NLR · September 2026", RULES, "Weekly limits, finalist reproducibility, and one selection for both rounds. No competition submission was made."),
        ("Scientific primary source", "Reid et al. · 1990", REID, "Contact Euler needs the arbitrary offset A. Source-position/depth inference is not a proof of a fault."),
        ("Scientific correction", "Reid & Thurston · 2014", SI, "Gravity/magnetic SI distinctions and limitations of single-source homogeneity for finite steps."),
        ("Official USGS · CC0 metadata", "GeoDAWN survey release", "https://www.usgs.gov/data/geodawn-airborne-magnetic-and-radiometric-surveys-northwestern-great-basin-nevada-and", "Terrain-draped magnetic/radiometric survey, variable clearance, 200/400 m nominal flight-line spacing. Metadata obtainable; altitude bulk audit still needed."),
        ("Official USGS", "Regional geophysical maps", "https://www.sciencebase.gov/catalog/item/628d4fabd34ef70cdba3c4a4", "Provisional, multi-source regional gravity compilation. Resampling does not create independent 100 m observations."),
        ("Official GDR · CC-BY-4.0", "INGENIOUS collection 1391", "https://gdr.openei.org/submissions/1391", "Free faults, geodesy, seismicity, shallow temperatures, paleo-geothermal features and well/spring chemistry. Coverage and observational bias need auditing."),
        ("Official USGS", "State Geologic Map Compilation", "https://pubs.usgs.gov/ds/1052/", "Original compilation context only. Does not authenticate the owner-derived SGMC raster used as a proxy here."),
        ("Official USGS publication", "Blind Gabbs Valley geothermal discovery", "https://pubs.usgs.gov/publication/70201803", "The reported discovery combined structural, geophysical, temperature and geochemical evidence and drilling. It does not validate an isolated Euler cluster."),
        ("Official USGS publication", "Structural discontinuities · Siler 2023", "https://www.usgs.gov/publications/structural-discontinuities-and-their-control-hydrothermal-systems-great-basin-usa", "Process-based stress/strain context for fault terminations and stepovers. Geometric favorability is not measured geothermal permeability."),
        ("Organizer staff", "Pixel-exact known-fault mask", "https://community.drivendata.org/t/scoring-clarification-are-known-usgs-ingenious-faults-masked-when-scoring-and-are-they-in-the-final-round-label-set/11516/4", "No automatic 300 m exclusion buffer. Off-mask predictions near an old trace can still incur penalties."),
        ("Official platform policy", "DrivenData Terms of Use", "https://www.drivendata.org/termsofuse/", "Automated monitoring is restricted. The scheduled feed below only uses USGS/GDR, not DrivenData."),
    ]
    cards = "".join(f'<article class="sourcecard"><span class="label">{esc(kind)}</span><h3><a href="{url}">{esc(title)} ↗</a></h3><p>{esc(fact)}</p></article>' for kind, title, url, fact in source_rows)
    sources = subhero("RESEARCH LIBRARY / OFFICIAL & PRIMARY SOURCES", "Sources with boundaries.", "Every source has a role and a limit. Official context does not authenticate a mirror; an academic method does not guarantee a resource; a proxy result is not a leaderboard score.")
    sources += f'''<section class="section twocol"><div>{cards}</div><aside><div class="callout"><p class="eyebrow">DATA PLACEMENT / COMPLETED</p><h3>Inputs restored autonomously.</h3><p>The 419 MB feature stack, template, known labels, exact frozen proxy and the 343-artifact prior corpus are in data/. Every part is hash checked. Caches stay out of Git.</p><p><strong>No GPU is required</strong> for these Euler experiments. No DrivenData login or private labels are available.</p><a href="data/acquisition-20261006.json">Source pins and receipt ↗</a></div><div class="notice"><strong>Mirrors are not official authentication.</strong><p>GitHub-hosted sibling copies are used because direct sandbox HTTPS to official/Dropbox download hosts failed. Feature identity is consistency-checked, not certified by the organizer.</p></div><h3>Irregularities worth reviewing</h3><ul class="micro"><li>Same SGMC basename, three different rasters. Only the GEMSDOE30 pin reproduces the frozen instrument.</li><li>CAT-HID held two latent defects (hidden set in its own flank; background in the hide fraction). Repaired 2026-10-06; every historical reading was zero.</li><li>H33’s 216-byte ZIP contains no TIFF; its actual TIFF was used for analysis.</li><li>History also contains a 110-byte header-only file and a one-pixel demo; byte-accounted, not falsely correlated.</li><li>Two old “NaN-outside” variants contain millions of NaNs inside the footprint; their all-finite companions establish exact storage equivalence.</li><li>The inherited frozen holdout gate is infeasible (18 of 16 truth-bearing blocks) and its incumbent circular.</li></ul><p><a href="research/scientific-library-20261006.md">Full claim-by-claim ledger</a></p></aside></section>
<section class="section" id="context"><p class="eyebrow">AUTOMATED CONTEXT / NO SCORE MONITORING</p><h2>USGS source freshness.</h2><p id="feed-status" aria-live="polite">Loading the dated official-source feed…</p><ul id="feed-events" class="eventlist"></ul><p class="micro">The Pages workflow refreshes the public ComCat context and USGS/GDR source probes daily. It preserves last-success timestamps, surfaces errors, and never changes the TIFF or promotes a candidate. Earthquakes are context, not confirmed faults or geothermal resources.</p><div class="linkrow"><a href="data/source-feed.json">Inspect source-feed JSON</a><a href="https://earthquake.usgs.gov/fdsnws/event/1/">Official ComCat API</a><a href="https://github.com/buffedlizard55-lab/GEMSDOE40/actions/workflows/pages.yml">Build / refresh history</a></div></section>'''
    page("sources.html", "Official-source research library", sources, "sources.html")

    root_landing = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0; url=docs/index.html"><title>GEMSDOE40 · Session-2 research downloads</title><link rel="canonical" href="docs/index.html"><link rel="stylesheet" href="docs/assets/contact.css"></head><body><main class="wrap subhero"><p class="kicker">GEMS / 40 · SESSION 2</p><h1>HOLD — DO NOT SUBMIT</h1><p>H13 (crest-binary) and H8 (trace-locked depth-KDE) are format-valid, unique versus 343 prior artifacts, and honestly gated: the off-catalogue proxy holdout failed for both. No weekly slot was used.</p><p><a class="button" href="docs/{link}" download>Download H13 research GeoTIFF ↓</a> <a class="button" href="docs/{h8link}" download>Download H8 GeoTIFF ↓</a></p><p><a class="button" href="docs/downloads/gemsdoe40-h8-asa-spi-depthkde-20261006T035031Z-b845d3ad449e-zeros.zip" download>Download H8-ASA analytic-signal GeoTIFF (.zip) ↓</a></p><p><a href="docs/index.html">Open the project site</a> · <a href="docs/executive-summary.html">Submission guide</a></p></main></body></html>'''
    (ROOT / "index.html").write_text(root_landing, encoding="utf-8")
    print("Built 8 evidence-driven pages and root redirect; no model, score, or promotion state changed.")


if __name__ == "__main__":
    main()
