#!/usr/bin/env python3
"""Write ``ref/meta/prior_corpus.md``: sha256, mass, live score, instrument inputs.

Every prior raster staged in ``ref/prior`` is hashed, and (for the files whose
organizer score is recorded) its live-anchored instrument inputs are recomputed
so the table can be re-derived from the bytes rather than trusted.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

import numpy as np
import rasterio

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from gemsdoe40.emission import calibrated_live_score, dot_credit_w  # noqa: E402

DATA = ROOT / "data"
PRIOR = ROOT / "ref" / "prior"
OUT = ROOT / "ref" / "meta" / "prior_corpus.md"


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for b in iter(lambda: fh.read(1 << 22), b""):
            h.update(b)
    return h.hexdigest()


def main() -> int:
    with rasterio.open(DATA / "sample_submission.tif") as ds:
        foot = np.isfinite(ds.read(1))
    with rasterio.open(DATA / "labels.tif") as ds:
        labels = ds.read(1) > 0
    with rasterio.open(DATA / "external" / "derived_sgmc_faults_100m_u8.tif") as ds:
        sgmc = ds.read(1) > 0
    truth = sgmc & ~labels
    idx = json.load(open(ROOT / "ref" / "meta" / "prior_index.json"))
    rows = []
    for p in sorted(PRIOR.glob("*.tif")):
        with rasterio.open(p) as ds:
            a = ds.read(1)
        inside = np.isfinite(a) & (a > 0) & foot & ~labels
        n = int(inside.sum())
        w = dot_credit_w(inside, truth) if n else 0.0
        live = None
        for key, meta in idx.items():
            if meta.get("live_score") is not None and Path(meta["path"]).name in p.name:
                live = meta["live_score"]
            elif meta.get("live_score") is not None and key == p.name:
                live = meta["live_score"]
        rows.append(dict(name=p.name, sha256=sha256(p), bytes=p.stat().st_size, mass=n,
                         w=w, live=live,
                         pred=calibrated_live_score(n, w) if n else 0.0,
                         catalogue_overlap=int((inside & labels).sum())))
    lines = [
        "# Prior-raster corpus (measured)",
        "",
        "Generated by `scripts/prior_corpus_report.py` from the bytes in `ref/prior/`.",
        "`mass` = emitted pixels inside the sample footprint excluding the catalogue;",
        "`w` = mean per-dot kernel credit against the off-catalogue surrogate truth",
        "(SGMC faults outside the provided catalogue) — the instrument input;",
        "`pred` = saturating live-score model reproduced from the sibling repository's",
        "fit to 12 organizer-scored artifacts (this file is a record, not a claim that",
        "any number here is an organizer score).",
        "",
        "| file | sha256 (first 16) | bytes | mass | w | live (reported) | pred |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in sorted(rows, key=lambda r: -(r["live"] or 0)):
        live = f"{r['live']}" if r["live"] is not None else "—"
        lines.append(f"| `{r['name']}` | `{r['sha256'][:16]}` | {r['bytes']:,} | {r['mass']:,} | "
                     f"{r['w']:.4f} | {live} | {r['pred']:.4f} |")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"[out] {OUT}  ({len(rows)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
